### ISSUE TITLE
Can not authorize

### ISSUE THREAD

**Issue by hispeedsurfer** [amralharazi/SPreview#1]
Hello Amaralharazi,

when the Spotify authorization screen appears I can not imput my username because the keyboard disappears right after I put the curson into textfield.

Error in XCode:  -[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID...

Do you have an idea how to solve the problem?

**Comment by amralharazi** [comment]
Hello hispeedsurfer,

Thank you for bringing this issue to my attention. 

Apparently, there must be some granted entitlements/permissions to open and interact with web pages on iOS apps. The error exactly was:

Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "((target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.rendering AND target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.networking AND target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.webcontent))" UserInfo={NSLocalizedFailureReason=((target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.rendering AND target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.networking AND target is not running or doesn't have entitlement com.apple.developer.web-browser-engine.webcontent))}>


To not deal with any of that, I changed the implementation of Spotify authorization to happen through Spotify app itself.

Mind you, I didn't do anything in case the app is not installed on the device, so you will have to fix that on your own. Or at least just show an alert to the user that they need to download Spotify first to grant permissions.

If you're interested in knowing more about the alternative approach I implemented, you can have a look on this:
https://medium.com/swlh/authenticate-with-spotify-in-ios-ae6612ecca91
